/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"


#ifndef _Included_com_example_mytest0126_JNI
#define _Included_com_example_mytest0126_JNI
#ifdef __cplusplus
extern "C" {
#endif



jint Java_com_example_mytest0126_JNI_connect1(JNIEnv *, jobject, jint);
jint Java_com_example_mytest0126_JNI_connect2(JNIEnv *, jobject, jint);
void Java_com_example_mytest0126_JNI_sendToServer1(JNIEnv *, jobject, jstring inf);
void Java_com_example_mytest0126_JNI_sendToServer2(JNIEnv *, jobject, jstring inf);
void Java_com_example_mytest0126_JNI_closeConnection1(JNIEnv *, jobject);
void Java_com_example_mytest0126_JNI_closeConnection2(JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
